#:schema https://json.schemastore.org/any.json

root = "."
testdata_dir = "testdata"

[build]
cmd = "true"
delay = 1000
entrypoint = ["make", "dev"]
include_ext = ["go", "html", "css", "env", "tpl", "tmpl"]
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "data",
    "testdata",
    "internal/web/dist/",
    "web/node_modules",
]
exclude_regex = ["_test.go", ".pb.go"]
log = "build-errors.log"
rerun_delay = 500

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[screen]
clear_on_rebuild = true
keep_scroll = true
